const Commando = require('discord.js-commando');
// const bot = new Commando.Client();

class MixTeamCommand extends Commando.Command
{
   
   constructor(client){
    super(client, {
        name: 'mixteam',
        group: 'pokemon',
        memberName: 'mixteam',
        description: 'Randomly generates a mix-tier team'
    })

   }

   async run(message, args)
   {
        var ouNames = ["Aerodactyl",
        "Blissey",
        "Celebi",
        "Claydol",
        "Cloyster",
        "Dugtrio",
        "Flygon",
        "Forretress",
        "Gengar",
        "Gyarados",
        "Heracross",
        "Jirachi",
        "Jolteon",
        "Magneton",
        "Metagross",
        "Milotic",
        "Porygon2",
        "Raikou",
        "Regice",
        "Salamence",
        "Skarmory",
        "Snorlax",
        "Starmie",
        "Suicune",
        "Swampert",
        "Tyranitar",
        "Zapdos",
        "Alakazam",
        "Arcanine",
        "Armaldo",
        "Articuno",
        "Blaziken",
        "Chansey",
        "Charizard",
        "Crobat",
        "Dodrio",
        "Donphan",
        "Dragonite",
        "Dusclops",
        "Entei",
        "Espeon",
        "Exeggutor",
        "Gardevoir",
        "Hariyama",
        "Jumpluff",
        "Jynx",
        "Kadabra",
        "Kingdra",
        "Lapras",
        "Ludiculo",
        "Machamp",
        "Marowak",
        "Medicham",
        "Miltank",
        "Moltres",
        "Ninjask",
        "Regirock",
        "Registeel",
        "Rhydon",
        "Sceptile",
        "Scizor",
        "Slaking",
        "Slowbro",
        "Smeargle",
        "Steelix",
        "Tauros",
        "Typhlosion",
        "Umbreon",
        "Ursaring",
        "Vaporeon",
        "Venusaur",
        "Weezing",
        "Zangoose"];
     var nuNames = ["Abra",
        "Aipom",
        "Anorith",
        "Arbok",
        "Ariados",
        "Beautifly",
        "Beedrill",
        "Bellossom",
        "Butterfree",
        "Cacturne",
        "Castform",
        "Charmeleon",
        "Chimecho",
        "Clamperl",
        "Corsola",
        "Crawdaunt",
        "Delcatty",
        "Delibird",
        "Dewgong",
        "Diglett",
        "Ditto",
        "Dragonair",
        "Drowzee",
        "Dunsparce",
        "Duskull",
        "Dustox",
        "Farfetch'd",
        "Flareon",
        "Furret",
        "Glalie",
        "Golbat",
        "Graveler",
        "Grovyle",
        "Haunter",
        "Hitmonchan",
        "Houndour",
        "Huntail",
        "Illumise",
        "Kecleon",
        "Kingler",
        "Koffin",
        "Lairon",
        "Ledian",
        "Lickitung",
        "Lileep",
        "Lombre",
        "Luvdisc",
        "Machoke",
        "Magby",
        "Magcargo",
        "Masquerain",
        "Mawile",
        "Metang",
        "Mightyena",
        "Minun",
        "Murkrow",
        "Noctowl",
        "Nosepass",
        "Octillery",
        "Omanyte",
        "Onix",
        "Parasect",
        "Pelipper",
        "Pidgeot",
        "Pikachu",
        "Piloswine",
        "Pineco",
        "Plusle",
        "Poliwhirl",
        "Ponyta",
        "Porygon",
        "Pupitar",
        "Quilava",
        "Raticate",
        "Relincanth",
        "Roselia",
        "Sableye",
        "Seadra",
        "Seaking",
        "Sealeo",
        "Seviper",
        "Shedinja",
        "Shelgon",
        "Shuckle",
        "Spinda",
        "Staryu",
        "Sudowoodo",
        "Sunflora",
        "Swalot",
        "Tangela",
        "Togetic",
        "Torkoal",
        "Trapinch",
        "Tropius",
        "Unown",
        "Venomoth",
        "Vigoroth",
        "Warortle",
        "Weepinbell",
        "Whiscash",
        "Wigglytuff",
        "Yanma"];
        var uuNames = ["Absol",
        "Aggron",
        "Altaria",
        "Ampharos",
        "Azumarill",
        "Banette",
        "Blastoise",
        "Breloom",
        "Camerupt",
        "Clefable",
        "Cradily",
        "Electabuzz",
        "Electrode",
        "Exploud",
        "Fearow",
        "Feraligatr",
        "Girafarig",
        "Gligar",
        "Golduck",
        "Golem",
        "Gorebyss",
        "Granbull",
        "Grumpig",
        "Hitmonlee",
        "Hitmontop",
        "Houndoom",
        "Hypno",
        "Kabutops",
        "Kangaskhan",
        "Lanturn",
        "Linoone",
        "Lunatone",
        "Magmar",
        "Manectric",
        "Mantine",
        "Meganium",
        "Misdreavus",
        "Mr.Mime",
        "Muk",
        "Nidoking",
        "Nidoqueen",
        "Ninetails",
        "Omastar",
        "Persian",
        "Pinsir",
        "Politoed",
        "Poliwrath",
        "Primape",
        "Quagsire",
        "Qwilfish",
        "Raichu",
        "Rapidash",
        "Sandslash",
        "Scyther",
        "Sharpedo",
        "Shiftry",
        "Slowking",
        "Sneasel",
        "Solrock",
        "Stantler",
        "Tentacruel",
        "Victreebel",
        "Vileplume",
        "Walrein",
        "Xatu"];
        var pokemonSelector1 = Math.floor(Math.random() * 73) + 1;
        var pokemonSelector2 = Math.floor(Math.random() * 73) + 1;
        var pokemonSelector3 = Math.floor(Math.random() * 65) + 1;
        var pokemonSelector4 = Math.floor(Math.random() * 65) + 1;
        var pokemonSelector5 = Math.floor(Math.random() * 102) + 1;
        var pokemonSelector6 = Math.floor(Math.random() * 102) + 1;
         message.reply(" " + ouNames[pokemonSelector1] + ", " + ouNames[pokemonSelector2]
         + ", " + uuNames[pokemonSelector3] + ", " + uuNames[pokemonSelector4] + ", " + nuNames[pokemonSelector5]
         + ", " + nuNames[pokemonSelector6]);
   }

}
module.exports = MixTeamCommand;