const Commando = require('discord.js-commando');
// const bot = new Commando.Client();

class NUMonCommand extends Commando.Command
{
   
   constructor(client){
    super(client, {
        name: 'numon',
        group: 'pokemon',
        memberName: 'numon',
        description: 'Randomly chooses a NU pokemon'
    })

   }

   async run(message, args)
   {
     var pokemonNames = ["Abra",
        "Aipom",
        "Anorith",
        "Arbok",
        "Ariados",
        "Beautifly",
        "Beedrill",
        "Bellossom",
        "Butterfree",
        "Cacturne",
        "Castform",
        "Charmeleon",
        "Chimecho",
        "Clamperl",
        "Corsola",
        "Crawdaunt",
        "Delcatty",
        "Delibird",
        "Dewgong",
        "Diglett",
        "Ditto",
        "Dragonair",
        "Drowzee",
        "Dunsparce",
        "Duskull",
        "Dustox",
        "Farfetch'd",
        "Flareon",
        "Furret",
        "Glalie",
        "Golbat",
        "Graveler",
        "Grovyle",
        "Haunter",
        "Hitmonchan",
        "Houndour",
        "Huntail",
        "Illumise",
        "Kecleon",
        "Kingler",
        "Koffin",
        "Lairon",
        "Ledian",
        "Lickitung",
        "Lileep",
        "Lombre",
        "Luvdisc",
        "Machoke",
        "Magby",
        "Magcargo",
        "Masquerain",
        "Mawile",
        "Metang",
        "Mightyena",
        "Minun",
        "Murkrow",
        "Noctowl",
        "Nosepass",
        "Octillery",
        "Omanyte",
        "Onix",
        "Parasect",
        "Pelipper",
        "Pidgeot",
        "Pikachu",
        "Piloswine",
        "Pineco",
        "Plusle",
        "Poliwhirl",
        "Ponyta",
        "Porygon",
        "Pupitar",
        "Quilava",
        "Raticate",
        "Relincanth",
        "Roselia",
        "Sableye",
        "Seadra",
        "Seaking",
        "Sealeo",
        "Seviper",
        "Shedinja",
        "Shelgon",
        "Shuckle",
        "Spinda",
        "Staryu",
        "Sudowoodo",
        "Sunflora",
        "Swalot",
        "Tangela",
        "Togetic",
        "Torkoal",
        "Trapinch",
        "Tropius",
        "Unown",
        "Venomoth",
        "Vigoroth",
        "Warortle",
        "Weepinbell",
        "Whiscash",
        "Wigglytuff",
        "Yanma"];
     var pokemonSelector = Math.floor(Math.random() * 102) + 1;
      message.reply(" " + pokemonNames[pokemonSelector]);
   }

}
module.exports = NUMonCommand;